### ISSUE TITLE
chore: extract all TODOs/FIXMEs to issues

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-rdm-migrator#121]
The code base of this module has already 14 of these and growing 😓

_Originally posted by @ppanero in https://github.com/inveniosoftware/invenio-rdm-migrator/pull/119#discussion_r1280201623_

**Comment by ppanero** [comment]
issues:
- https://github.com/inveniosoftware/invenio-rdm-migrator/issues/124
- https://github.com/inveniosoftware/invenio-rdm-migrator/issues/123
- https://github.com/inveniosoftware/invenio-rdm-migrator/issues/122
