### ISSUE TITLE
debezium configuration improvements

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-migrator#123]
- [ ] ~~datetimes should come in UTC ISO format, currently they come in microseconds, forcing a division in many places of the code (search for `1_000_000`).~~
    - Not possible since the [TimestampConverter](https://docs.confluent.io/platform/current/connect/transforms/timestampconverter.html) doesn't work "globally", requires each field to be specified and doesn't support nested fields (i.e. `after.created` wouldn't work).
- [ ] ~~jsonb columns should be actual dictionaries, no escaped strings.~~
    - Not possible, unfortunately, unless we write some custom transform Java class...
- [x] Ignore `transactions`, `record_metadata_revision` and `sipstrore` related tables (maybe more)
    - [x] In **sandbox** ignore `files_files` for file integrity check

**Comment by slint** [comment]
Closing, since we managed some of the fixes, but not everything unfortunately...
