### ISSUE TITLE
make some steps optional

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-migrator#24]
When running a stream we might want to:
- Only _prepare_ the data (e.g. dump csv) but not load. Then this last step should be optional (per run)
- Validation, should we be able to run without it?
- At the moment, _cleanup_ is a per run option, should it stay like that or be an attribute of the load (or both)

**Comment by kpsherva** [comment]
ensure the dependent object migration fe. pid and record do not generate orphan artifacts in the database (when the record migration fails, we don't want the PID to be left behind in the DB)

**Comment by ppanero** [comment]
This has been implemented
