### ISSUE TITLE
migrator: fix psycopg installation

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-rdm-migrator#33]
[Installing the module](https://github.com/inveniosoftware/invenio-rdm-migrator/blob/master/setup.cfg#L29) in the current state throws errors about the `libq` library. Check how we can solve this.

See https://www.psycopg.org/psycopg3/docs/api/pq.html, it might be solved by just requiring ` psycopg[c]>=3.1.4`

**Comment by ntarocco** [comment]
Maybe to document: On MacOS, you need to have `libpq` installed (which contains `pg_config` bin), see https://stackoverflow.com/a/67757077/675178

**Comment by slint** [comment]
`psycopg[binary]` might also be an option that won't require dependencies (similar to `psycopg2-binary`).

Note: the reason we're using the library in the first place is because the old version doesn't have support for some of the `COPY ...` helpers we're using.

**Comment by ntarocco** [comment]
> psycopg[binary] might also be an option that won't require dependencies (similar to psycopg2-binary).

This was not enough for me, locally it was looking for `pg_config` bin.

**Comment by kpsherva** [comment]
https://www.psycopg.org/install/

**Comment by ntarocco** [comment]
From the doc: https://www.psycopg.org/docs/install.html
```
If you are the maintainer of a published package depending on psycopg2 you shouldn’t use psycopg2-binary as a module dependency. For production use you are advised to use the source distribution.
```
we can close this issue and simply document that `libpq-dev` is now needed when installing this module.
