### ISSUE TITLE
load: update sequences in one transaction/SQL command

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-rdm-migrator#58]
One thing to investigate in the future is the ability to do this with a single SQL statement (or in one transaction). I see some ideas that we can combine from this [SO thread](https://stackoverflow.com/questions/244243/how-to-reset-postgres-primary-key-sequence-when-it-falls-out-of-sync).

_Originally posted by @slint in https://github.com/inveniosoftware/invenio-rdm-migrator/pull/54#pullrequestreview-1410301089_

**Comment by ppanero** [comment]
https://wiki.postgresql.org/wiki/Transactional_DDL_in_PostgreSQL:_A_Competitive_Analysis

**Comment by ppanero** [comment]
I think this is not needed anymore since updates come now as part of the actions stream. re-open if we need to reconsider.
