### ISSUE TITLE
record files as post_hook

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-migrator#95]
Implement record files in the same fashion as [draft files](https://github.com/zenodo/zenodo-rdm/issues/311) to avoid relying on `_files`.

This would face a similar problem as the versioning table generator. Since records and drafts use the same load class, it means that the post hooks for records and drafts will execute twice (once for each stream). 
During the first run of the load class (records), the drafts post hook will execute but its effect will be nullable since the `rdm_drafts_metadata` table would be empty. However, on the second execution (drafts) the records post hook execution will cause one PK collision exception per row (order of millions)

**Comment by slint** [comment]
Implemented as a reusable [utlity class ](https://github.com/inveniosoftware/invenio-rdm-migrator/blob/72c61592c2de1bc50c82ef75c412a523debdef11/invenio_rdm_migrator/streams/records/table_generators/utils.py#L15).
